apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: docker-registry
  namespace: prometheus-fabric
spec:
  type: kv-v2

  # mount path
  mount: concourse

  # path of the secret
  path: shared/docker-registry

  # dest k8s secret
  destination:
    name: docker-registry
    create: true
    type: "kubernetes.io/dockerconfigjson"

  # static secret refresh interval
  refreshAfter: 30s