apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-creds
  namespace: prometheus-fabric
spec:
  type: kv-v2
  # mount path
  mount: concourse
  # path of the secret
  path: shared/grafana-creds
  # dest k8s secret
  destination:
    name: grafana-creds
    create: true
  # static secret refresh interval
  refreshAfter: 30s
