apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-creds
  namespace: prometheus-fabric
spec:
  type: kv-v2
  # mount path
  mount: concourse
  # path of the secret
  path: enterprise-archive/ep-ea-grafana-postgres-smarsh-${ARGOCD_ENV_CLOUD_REGION}/db-instance
  # dest k8s secret
  destination:
    name: postgres-creds
    create: true
  # static secret refresh interval
  refreshAfter: 30s